Update Dockerfile
micro-ROS/docker pull request #101
Opened 2023-09-13 08:46 UTC by ncnynl

Change entry script call

2023-09-13 08:51 UTC, pablogs9 requested changes

2023-09-13 08:51 UTC, pablogs9 commented on micro-ROS-static-library-builder/Dockerfile
> +#ENTRYPOINT ["/entrypoint.sh"]
```suggestion
```

Not required

2023-09-13 14:48 UTC, ncnynl reviewed
Remove redundant code

2023-09-14 05:55 UTC, pablogs9 commented
Could you explain the rationale of this PR a bit?

2023-09-14 06:02 UTC, ncnynl reviewed
ENTRYPOINT ["/entrypoint.sh"] it will have permission issues, causing it to not work properly when running docker container.  so change into ENTRYPOINT ["/bin/sh", "/entrypoint.sh"] can fixed it

2023-09-14 06:44 UTC, pablogs9 commented
@mergify backport humble rolling

2023-09-14 06:44 UTC, merged